import { Task } from './task.model';

export const dummyData: Task[] = [
  {
    id: '1',
    title: 'Implement login functionality',
    name: 'Login',
    dueTo: '2024-03-15',
    priority: 'high',
    status: 'in-progress',
    assignees: [{ id: '1', name: 'John Doe' }, { id: '7', name: 'Olivia Martinez' }],
  },
  {
    id: '2',
    title: 'Refactor component structure',
    name: 'Refactor',
    dueTo: '2024-03-20',
    priority: 'medium',
    status: 'idle',
    assignees: [{ id: '2', name: 'Jane Smith' }],
  },
  {
    id: '3',
    title: 'Fix bug in API endpoint',
    name: 'Bug Fix',
    dueTo: '2024-03-17',
    priority: 'high',
    status: 'in-progress',
    assignees: [{ id: '3', name: 'Alice Johnson' }],
  },
  {
    id: '4',
    title: 'Add new feature',
    name: 'New Feature',
    dueTo: '2024-03-25',
    priority: 'medium',
    status: 'idle',
    assignees: [{ id: '4', name: 'Bob Williams' }],
  },
  {
    id: '5',
    title: 'Optimize database queries',
    name: 'Optimization',
    dueTo: '2024-03-18',
    priority: 'high',
    status: 'done',
    assignees: [{ id: '5', name: 'Eva Brown' }, { id: '6', name: 'Michael Wilson' }],
  },
  {
    id: '6',
    title: 'Write unit tests',
    name: 'Unit Tests',
    dueTo: '2024-03-22',
    priority: 'medium',
    status: 'idle',
    assignees: [{ id: '6', name: 'Michael Wilson' }],
  },
  {
    id: '7',
    title: 'Design new UI component',
    name: 'UI Design',
    dueTo: '2024-03-16',
    priority: 'high',
    status: 'in-progress',
    assignees: [{ id: '7', name: 'Olivia Martinez' }],
  },
  {
    id: '8',
    title: 'Review code changes',
    name: 'Code Review',
    dueTo: '2024-03-19',
    priority: 'medium',
    status: 'idle',
    assignees: [{ id: '8', name: 'William Jones' }],
  },
  {
    id: '9',
    title: 'Deploy to production',
    name: 'Deployment',
    dueTo: '2024-03-23',
    priority: 'high',
    status: 'done',
    assignees: [{ id: '9', name: 'Sophia Garcia' }],
  },
  {
    id: '10',
    title: 'Update documentation',
    name: 'Documentation',
    dueTo: '2024-03-21',
    priority: 'medium',
    status: 'idle',
    assignees: [{ id: '10', name: 'Liam Brown' }],
  },
];
